### ISSUE TITLE
解码错误

### ISSUE THREAD

**Issue by pine1212** [forecho/Quicksilver#12]
Traceback (most recent call last):
  File "/Quicksilver/spider/ximalaya.py", line 75, in album
    episode.publication_date = self.reduction_time(item['time_until_now'], item['formatted_created_at'])
  File "/Quicksilver/spider/ximalaya.py", line 90, in reduction_time
    date = datetime.strptime(created_at, "%m月%d日 %H:%M")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u6708' in position 1: ordinal not in range(128)

Traceback (most recent call last):
  File "app.py", line 23, in <module>
    main()
  File "app.py", line 20, in main
    myinstance.album()
  File "/Quicksilver/spider/ximalaya.py", line 85, in album
    self.podcast.rss_file('ximalaya/%s.rss' % self.album_id, minimize=True)
  File "/usr/local/lib/python2.7/dist-packages/podgen/podcast.py", line 690, in rss_file
    fd.write(rss)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 274-282: ordinal not in range(128)

**Comment by forecho** [comment]
因为你是 Python2 ，把这两行代码注释打开试试 https://github.com/forecho/Quicksilver/blob/master/app.py#L8-L9
